### ISSUE TITLE
Run tests on OSX using Travis-CI

### ISSUE THREAD

**Issue by sverhoeven** [3D-e-Chem/knime-klifs#4]
See https://docs.travis-ci.com/user/osx-ci-environment/

**Comment by AJK-dev** [comment]
Updates not sufficient, on Travis the testflow hangs after the testflow.

**Comment by sverhoeven** [comment]
Fixed in 477ee22d132fd0779f5c23c48799e6511b85abba

See Travis CI OS X job at https://travis-ci.org/3D-e-Chem/knime-klifs/jobs/196923439
